[versions]
neogradle = "7.0.159"
neo = "21.1.8"

[libraries]
neo = { group = "net.neoforged", name = "neoforge", version.ref = "neo" }

[plugins]
ng-userdev = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }