[versions]
neogradle = "7.0.180"
neo = "21.4.81-beta"

[libraries]
neo = { group = "net.neoforged", name = "neoforge", version.ref = "neo" }

[plugins]
ng-userdev = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }