name: Publish package to GitHub Packages
on:
  release:
    types: [created, edited]
    tags: neoforge-1.21.1-*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch correct branch
        run: git fetch origin 1.21.1:staging
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
        env:
          VERSION: ${{ github.event.tag_name }}
        with:
          gradle-version: 8.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish package
        run: ./gradlew publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
